### PR TITLE
Added the step_rewire method

### PR DESCRIPTION
**Pull request by samwestby**
This method is not implemented by default. Rewiring methods that allow for step-by-step rewiring should implement the step_rewire method. Methods that do not allow for it do not have to implement it.

### CODE REVIEW

**Comment by jkbren** [comment]
This is great -- let's change `rewire` to `full_rewire`, and instead of returning `G`, do a `raise NotImplementedError`, for consistency with both. Then for new techniques implemented, they seem to fall between two different categories of rewiring:

1. First is an algorithm that iteratively changes edges in the network, step by steps, for `timesteps=T` iterations. This technique has two ways to think about rewiring. The `step_rewire` is the technique that rewires a single edge in the original graph. Then `full_rewire` is a function that calls `step_rewire` repeatedly.
2. The second class of rewiring algorithms that we may come up against are ones that are more optimization-oriented. That is, the notion of timesteps is less obvious than in the class above. Here, we will likely find techniques that do not have a clear `step_rewire` capability and instead only really make sense to implement `full_rewire`.

There are, of course, optimization-based algorithms that make sense with `step_rewire` and `full_rewire`. In that case, people implementing a technique should include both functions in their Rewire classes.

**Comment by sdmccabe** [comment]
Can you reformat the file? `black base.py`. Alternately, I think all it's going to do is add an extra line before `def step_rewire()`, so you can just add that manually.

**Comment by samwestby** [comment]
Makes sense to me. I'll update the class and figure out the ubuntu, python 3.9 merge error

**Comment by sdmccabe** [comment]
That error is just indicating that the file needs to be reformatted with black.

**Comment by samwestby** [comment]
Now there's an issue with the algebraic_connectivity.py file. I'll take a look

**Comment by sdmccabe** [comment]
The existing tests need to be rewritten to accommodate `full_rewire()` vs. `step_rewire()`.

**Comment by samwestby** [comment]
I'm still getting build errors 
` /home/runner/work/netrw/netrw/netrw/rewire/algebraic_connectivity.py:10: DeprecationWarning: invalid escape sequence \i`
Not really sure why there's an issue, because I didn't modify algebraic_connectivity.py at all. It appears to be an issue with the """ block comment. Any ideas?

**Pull request merged**
